apiVersion: sources.knative.dev/v1
kind: ContainerSource
metadata:
  name: cloudevents-poller
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
  template:
    spec:
      containers:
      - image: docker.io/juliandeutsch/cloudevents-poller:0.0.1
        env:
        - name: POWER_STATUS_URL
          value: http://battery-simulator-svc.monitoring.svc.cluster.local:8080/status
        - name: PERIOD
          value: 30s

